config/routes.rb
Sem7curs::Application.routes.draw do

  authenticated :user do
    root :to => 'users#show'
  end
  
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    member do
      get :following, :followers
    end
    resources :photo_albums do
      resources :photos
    end
    resources :posts
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]
   
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_one :information, :dependent => :destroy       
  
  has_many :posts
  has_many :comments
  
  has_many :photo_albums, :dependent => :destroy
  
  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'recipient_id'
  
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :followed_users, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id", :class_name => "Relationship", :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  attr_accessible :name, :surname, :email, :password, :password_confirmation, :remember_me, :confirmed_at

  validates_presence_of :name, :surname, :email
  
  after_create :build_details

  def build_details
    self.build_information
    self.save!
    self.photo_albums.create(:title => "Main album")
  end
  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.paginate(:page => params[:page], :per_page => 30)
  end

  def show
    if params[:id].nil?
      @user = current_user
    else 
      @user = User.find params[:id]
    end
    @posts = @user.posts
  end
  
  def edit
    @user = User.find params[:id]
    @information = @user.information
    @photo = @user.information.photo || Photo.new
  end
  
  def update
    @user = User.find params[:id]
    @user.information.photo = Photo.create params[:photo]
    @user.information.photo.save!
    respond_to do |format|
      if @user.information.update_attributes(params[:information])
        format.html { redirect_to @user, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_profile.html.erb
<%= form_for(@information, :url => user_path(@user.id), :html => { :method => :put, :class => 'form-horizontal' }) do |f| %>

<div class="form-inputs">
	<fieldset>
		<%= fields_for @photo do |ph| %>
			<div class="control-group">
				<%= ph.label 'Avatar', :class => 'control-label' %>
				<%= ph.text_field :url, :class => 'control-input' %>
			</div>
		<% end %>
		<div class="control-group">
			<%= f.label 'Country', :class => 'control-label' %>
			<%= f.select :country_id, Country.all.collect { |country| [country.title, country.id] }, :include_blank => true %>
		</div>
		<div class="control-group">
			<%= f.label :gender, :class => 'control-label' %>
			<%= f.select(:gender, %w{ M F }, :include_blank => true) %>
		</div>
		<div class="control-group">
			<%= f.label :date_of_birth, :class => 'control-label' %>
			<%= f.date_select(:date_of_birth) %>
		</div>

		<div class="control-group">
			<%= f.label :about, :class => 'control-label' %>
			<%= f.text_area :about, :class => 'control-input control-text-area'%>
		</div>

	</fieldset>
</div>

<div class="form-actions">
	<div class="for-buttons">
		<%= f.submit "Update", :class => 'btn btn-primary' %>
	</div>
</div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form" class="button-follow">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_left_menu.html.erb
<div class="sidebar-nav">
	<ul class="nav nav-list">
		<li>
			<h3><%= link_to "My Page", root_path %></h3>
		</li>
		<li>
			<h3><%= link_to "Messages", root_path %></h3>
		</li>
		<li>
			<h3><%= link_to "Photos", photo_albums_path %></h3>
		</li>
		<li>
			<h3><%= link_to "Followers", root_path %></h3>
		</li>
		<li>
			<h3><%= link_to "Followings", root_path %></h3>
		</li>
		<hr />
		<li>
			<h3><%= link_to "Settings", edit_user_path(@user.id) %></h3>
		</li>
	</ul>
</div>

app/views/users/_new_post.html.erb
<%= link_to "New post", new_user_post_path(@user)%>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
  	Following: 
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
  </a>
  <a href="<%= followers_user_path(@user) %>">
  	Followers: 
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </a> 
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_users_avatar.html.erb
<div class="avatar">
	<% if @user.information.photo and !@user.information.photo.blank? %>
		<%= image_tag @user.information.photo.url, :size => "300x300" %>
	<% else %>
		<%= image_tag "no-avatar.jpg", :size => "250x250" %>
	<% end %>
	
	<% if @user == current_user %>
		<%= link_to "Change profile photo", edit_user_path(current_user) %>
	<% else %>
		<h3><%= link_to "View Photos", user_photo_albums_path(@user) %></h3>
	<% end %>	
</div>

app/views/users/_users_information.html.erb
<dl class="dl-horizontal">
	<% if @user.information.date_of_birth and !@user.information.date_of_birth.blank? %>
	<dt>
		<strong>Date of Birth:</strong>
	</dt>
	<dd>
		<%= "#{@user.information.date_of_birth.day}.#{@user.information.date_of_birth.month}.#{@user.information.date_of_birth.year}"%>
	</dd>

	<% end %>
	<% if @user.information.gender and !@user.information.gender.empty? %>
	<dt>
		<strong>Gender:</strong>
	</dt>
	<dd>
		<%= @user.information.gender %>
	</dd>
	<% end %>

	<% if @user.information.country_id %>
	<dt>
		<strong>Country:</strong>
	</dt>
	<dd>
		<%= Country.find_by_id(@user.information.country_id).title %>
	</dd>
	<% end %>

	<% if @user.information.city_id %>
	<dt>
		<strong>City:</strong>
	</dt>
	<dd>
		<%= City.find_by_id(@user.information.city_id).title %>
	</dd>
	<% end %>

	<% if @user.information.about and !@user.information.about.empty? %>
	<dt>
		<strong>About:</strong>
	</dt>
	<dd>
		<%= @user.information.about %>
	</dd>
	<% end %>
	<br/>
	<% if @user == current_user %>
	<dd>
		<%= link_to "Change", edit_user_path(current_user) %>
	</dd>
	<% end %>
	
</dl>

app/views/users/_users_posts.html.erb
<h2><%= "#{@user.name}'s posts"%></h2>
<% if @posts and !@posts.blank? %>
	<% @posts.each do |post| %>
		<%= post.content %>
		<hr/>
		<%= post.posted_date %>
	<% end %>
<% else %>
	No posts made by this user
<% end %>

app/views/users/edit.html.erb
<div class="right-page-box">
	<ul class="nav nav-pills" id="settingsTab">
		<li class="active">
			<a href="#profile">Profile</a>
		</li>
		<li>
			<a href="#account">Account</a>
		</li>
		<li>
			<a href="#settings">Settings</a>
		</li>
	</ul>
	<div class="tab-content  well">
		<div class="tab-pane active" id="profile">
			<%= render 'edit_profile'%>

		</div>
		<div class="tab-pane" id="account">
			account
		</div>
		<div class="tab-pane" id="settings">
			settings
		</div>
	</div>
</div>

<script>
	$('#settingsTab a').click(function(e) {
		e.preventDefault();
		$(this).tab('show');
	})
</script>

app/views/users/index.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Last sign in at</th>
    <th>Registration date</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.name} #{user.surname}", user_path(user.id) %></td>
        <td>
          <%=user.last_sign_in_at %>
        </td>
        <td><%=  user.created_at.to_date %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate(@users) %>

app/views/users/show.html.erb
<div class="row well right-page-box">

	<div class="page-header red-name">
		<h1> <%= "#{@user.name} #{@user.surname}" %>
		<div class="pull-right darken">
		<% if @user == current_user %>
			(your page)
		<% else %>
			<%= render 'follow_form' %>
		<% end %> 
		</div> 
		</h1>
	</div>


	<div class="span4">

		<%= render 'users_avatar'%>
		
	</div>
	<div class="span5">

		<%= render 'users_information'%>

	</div>
	<div class="span2">
		<h3> <%= render 'stats' %> </h3>
	</div>

	<div class="span11">
		<hr/>
		<%= render 'users_posts' %>
		<br/>
		<% if current_user.id == @user.id %>
		<%= render 'new_post' %>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
Follow