config/routes.rb
Sem7curs::Application.routes.draw do

  authenticated :user do
    root :to => 'users#show'
  end
  
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    member do
      get :following, :followers
    end
    resources :photo_albums do
      resources :photos
    end
    resources :posts
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]
   
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :content, :posted_date, :url

  belongs_to :photo_album
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @photos = Photo.find_all_by_user_id(current_user.id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end
  
  def new
    @photo = Photo.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end
  
  def create
    @photo = Photo.new(params[:photo], :posted_date => DateTime.now)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully added.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photo_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/edit.html.erb
<h1>PhotoAlbums#edit</h1>
<p>Find me in app/views/photo_albums/edit.html.erb</p>

app/views/photos/index.html.erb
<h1>PhotoAlbums</h1>
<% if @photo_albums %>
	<% @photo_albums.each do |album|%>
		<div class="span3">
			<%= image_tag "empty_album_icon.jpg" %>
			<h3><%= link_to album.title, user_photo_album_path(current_user.id, album.id) %></h3>
		</div>
	<% end %>
<% else %>
	<% No photo albums%>
<% end %>

<%= link_to 'Add new album', new_user_photo_album_path%>

app/views/photos/new.html.erb
<%= form_for(@photo) do |f| %>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/show.html.erb
<h1><%= @photo_album.title %></h1>
<% if @photo_album.photos %>
	<% @photo_album.photos.each do |photo|%>
		<div class="span3">
			<%= image_tag "empty_album_icon.jpg" %>
			<h3><%= link_to photo.url, user_photo_album_photo_path(current_user.id, album.id, photo.id) %></h3>
		</div>
	<% end %>
<% else %>
	<% Empty album %>
<% end %>

<%= link_to 'Add new photo', new_user_photo_album_photo_path%>