config/routes.rb
Sem7curs::Application.routes.draw do

  authenticated :user do
    root :to => 'users#show'
  end
  
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    member do
      get :following, :followers
    end
    resources :photo_albums do
      resources :photos
    end
    resources :posts
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]
   
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :posted_date, :user_id
  
  has_many :comments, :dependent => :destroy
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_user
  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    @posts = @user.posts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    #@post = Post.new
    @post = @user.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(params[:post])
    @post = @user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        #format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.html { redirect_to [@user, @post], notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      #format.html { redirect_to posts_url }
      format.html { redirect_to user_posts_path(@user) }
      format.json { head :no_content }
    end
  end
  
  def load_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@user, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', user_post_path(@user, @post) %> |
<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
  	<td><%= post.content %></td>
  </tr>
  <tr>
    <td><%= post.created_at %> by <%= link_to "#{post.user.name} #{post.user.surname}", user_path(post.user_id) %></td>
  </tr>
  <tr>
    <td><%= link_to 'Show', user_post_path(@user, post)%></td>
    <td><%= link_to 'Edit', edit_user_post_path(@user, post) %></td>
    <td><%= link_to 'Destroy', [@user, post], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_user_post_path(@user) %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_user_post_path(@user, @post) %> |
<%= link_to 'Back', user_posts_path(@user) %>