config/routes.rb
Sem7curs::Application.routes.draw do

  authenticated :user do
    root :to => 'users#show'
  end
  
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    member do
      get :following, :followers
    end
    resources :photo_albums do
      resources :photos
    end
    resources :posts
    resources :messages
  end
  
  resources :relationships, only: [:create, :destroy]
   
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  attr_accessible :photo_id
  belongs_to :information
  belongs_to :photo
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :title
  belongs_to :country
  has_many :informations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :posted_date
  
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :title, :iso_two_letter_code
  has_many :cities
end

app/models/information.rb
class Information < ActiveRecord::Base
  attr_accessible :avatar, :photo, :photo_attributes, :photo_id, :country_id, :city_id, :date_of_birth, :gender, :about
    
  belongs_to :user
  belongs_to :city
  has_one :avatar #
  has_one :photo, :dependent => :destroy, :through => :avatar    # change maybe!
  #has_one :photo
  #accepts_nested_attributes_for :photo  #
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :title, :content, :sender, :recipient, :sender_id, :recipient_id
  
  belongs_to :sender, :class_name => 'User'
  belongs_to :recipient, :class_name => 'User'
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :content, :posted_date, :url

  belongs_to :photo_album
end

app/models/photo_album.rb
class PhotoAlbum < ActiveRecord::Base
  attr_accessible :title
  
  belongs_to :user
  has_many :photos
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :posted_date, :user_id
  
  has_many :comments, :dependent => :destroy
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id

  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"
  
  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
  
  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  has_one :information, :dependent => :destroy       
  
  has_many :posts
  has_many :comments
  
  has_many :photo_albums, :dependent => :destroy
  
  has_many :sent_messages, :class_name => 'Message', :foreign_key => 'sender_id'
  has_many :received_messages, :class_name => 'Message', :foreign_key => 'recipient_id'
  
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :followed_users, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id", :class_name => "Relationship", :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  attr_accessible :name, :surname, :email, :password, :password_confirmation, :remember_me, :confirmed_at

  validates_presence_of :name, :surname, :email
  
  after_create :build_details

  def build_details
    self.build_information
    self.save!
    self.photo_albums.create(:title => "Main album")
  end
  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_user
  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    @posts = @user.posts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    #@post = Post.new
    @post = @user.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    #@post = Post.new(params[:post])
    @post = @user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        #format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.html { redirect_to [@user, @post], notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    #@post = Post.find(params[:id])
    @post = @user.posts.find(params[:id])
    @post.destroy

    respond_to do |format|
      #format.html { redirect_to posts_url }
      format.html { redirect_to user_posts_path(@user) }
      format.json { head :no_content }
    end
  end
  
  def load_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/photo_albums_helper.rb
module PhotoAlbumsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_left_menu.html.erb
<div class="sidebar-nav">
	<ul class="nav nav-list left-menu">
		<li>
			<h3><%= link_to "My Page", root_path %></h3>
		</li>
		<li>
			<h3><%= link_to "Messages", user_messages_path(current_user) %></h3>
		</li>
		<li>
			<h3><%= link_to "Photos", user_photo_albums_path(current_user) %></h3>
		</li>
		<li>
			<h3><%= link_to "Following", following_user_path(current_user) %></h3>
		</li>
		<li>
			<h3><%= link_to "Followers", followers_user_path(current_user)  %></h3>
		</li>
		<hr />
		<li>
			<h3><%= link_to "Settings", edit_user_path(current_user) %></h3>
		</li>
	</ul>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-inner">
  <div class="container-fluid">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <%= link_to "My Social Network", root_path, :class => 'brand' %>
    <div class="nav-collapse collapse">
      <ul class="nav">
      	<li>
      		<%= link_to 'Community', users_path%>
      	</li>
      	<li>
      		<%= link_to 'Tab1', root_path%>
      	</li>
      	<li>
      		<%= link_to 'Tab2', root_path%>
      	</li>
      </ul>
      <ul class="nav pull-right">
  	    <% if user_signed_in? %>
	    <li>
	      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
	    </li>
	    <% else %>
	    <li>
	      <%= link_to 'Login', new_user_session_path %>  
	    </li>
	    <% end %>
	    <% if user_signed_in? %>
	    <li>
	      <%= link_to "Logged in as #{current_user.name} #{current_user.surname}", user_path(current_user.id) %>
	    </li>
	    <% else %>
	    <li>
	      <%= link_to 'Sign up', new_user_registration_path %>
	    </li>
	    <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_sign_in_form.html.erb
<div class="container">
  <form class="form-signin">
    <h2 class="form-signin-heading">Please sign in</h2>
    <input type="text" class="input-block-level" placeholder="Email address">
    <input type="password" class="input-block-level" placeholder="Password">
    <label class="checkbox">
      <input type="checkbox" value="remember-me"> Remember me
    </label>
    <button class="btn btn-large btn-primary" type="submit">Sign in</button>
  </form>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>My Social Network</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
    	
      <%= render 'layouts/navigation' %>
      
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
      	<% if current_user %>
      	  <div class="span2">

			<%= render 'layouts/left_menu'%>

		  </div>
		  <div class="span10">
      
	    	<%= yield %>
	    	
	      </div>
		<% else %>
      
	    	<%= yield %>
	    	
		<% end%>

	    
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; My Social Network 2012</p>
      </footer>

    </div><!--/.fluid-container-->


  </body>
</html>